export const site = {
  name: "Nthtake",
  tagline: "Send the client the work. Get paid. Then give them the clean files.",
  nav: [
    { href: "#how", label: "How" },
    { href: "#feedback", label: "Feedback" },
    { href: "#pricing", label: "Pricing" },
    { href: "#questions", label: "Questions" },
  ],
  hero: {
    badge: "For video editors & designers",
    line1: "Get paid before you",
    line2Before: "hand over the ",
    rotating: ["final files.", "clean master.", "high-res export.", "source project."] as const,
    body: "Send a watermarked preview. Your client reviews it, approves it, pays, and the clean files unlock.",
    waitlistLabel: "Work email",
    waitlistPlaceholder: "you@studio.com",
    waitlistCta: "Get early access to Nthtake",
    waitlistSending: "Sending",
    waitlistSuccess: "Spot reserved for",
    waitlistError: "Enter a work email.",
    proof: ["Video Editors", "Graphic Designers", "Creative Agencies"],
  },
  tools: [
    "Premiere",
    "After Effects",
    "DaVinci",
    "Figma",
    "Photoshop",
    "Final Cut",
  ],
  stats: {
    kicker: "The payment problem",
    titleBefore: "Chasing your own ",
    titleAccent: "money.",
    body: "You send the final file. Client says: I'll pay tomorrow. Tomorrow becomes next week. Now you're chasing your own money. Nthtake keeps the final files locked until you're paid.",
    items: [
      { value: "0", label: "Awkward follow-ups" },
      { value: "0%", label: "Commission taken" },
      { value: "1", label: "Link for review & pay" },
      { value: "Instant", label: "Master unlock" },
    ],
  },
  how: {
    kicker: "How it works",
    titleBefore: "Preview. Feedback. ",
    titleAccent: "Get paid.",
    cards: [
      {
        title: "1. Send the preview",
        description:
          "Client gets the full work with a watermark.",
      },
      {
        title: "2. Get feedback",
        description:
          "They comment directly on the work.",
      },
      {
        title: "3. Make changes",
        description:
          "Keep each version and its feedback together.",
      },
      {
        title: "4. Get paid & unlock",
        description:
          "Client approves and pays. Clean final files become available.",
      },
    ],
  },
  studio: {
    kicker: "AI assistance",
    titleBefore: "Turn client comments into a ",
    titleAccent: "to-do list",
    body: "Client gives feedback. Nthtake helps turn that feedback into a clear list of changes for the next version.",
  },
  review: {
    kicker: "The feedback problem",
    titleBefore: "Show them exactly what you ",
    titleAccent: "mean.",
    body: "Click the exact part you want changed, leave a comment, and keep every request attached to the right version. No more guessing what “that part” means.",
  },
  unlock: {
    kicker: "The gate",
    titleBefore: "Watermarked preview. Locked ",
    titleAccent: "master.",
    body: "Your client can watch or view the whole file. But they cannot download the clean version until they pay the invoice.",
    holdLabel: "Hold to unlock",
    lockedLabel: "PREVIEW → UNPAID",
    unlockedLabel: "MASTER → PAID",
    url: "[ NTHTAKE / PREVIEW ]",
  },
  takes: {
    kicker: "Versions",
    titleBefore: "Take 1 → Feedback → Take 2 → ",
    titleAccent: "Final.",
    before: "Take 1 · comments",
    after: "Take 2 · current version",
  },
  updates: {
    kicker: "Updates",
    titleBefore: "Send the take, not a ",
    titleAccent: "recap.",
  },
  faq: {
    badge: "Questions",
    title: "How does it actually work?",
    items: [
      {
        id: "q1",
        question: "Does the client pay before they see the work?",
        answer:
          "No. They watch the entire watermarked preview. Payment is required to download the clean final files, not to review the work.",
      },
      {
        id: "q2",
        question: "Can they just screen-record the preview?",
        answer:
          "The watermark is visible on the screen. A screen record will still have the watermark. They have to pay to get the clean files.",
      },
      {
        id: "q3",
        question: "How do revisions work?",
        answer:
          "Each time you upload, it creates a new version. The client's feedback stays attached to that specific version.",
      },
      {
        id: "q4",
        question: "How does the AI work?",
        answer:
          "If the client leaves messy comments, Nthtake can turn those comments into a simple bulleted list of changes for you to make.",
      },
      {
        id: "q5",
        question: "What does it cost?",
        answer:
          "Nthtake takes 0% commission on your client payments. We charge a simple, flat monthly subscription to use the platform.",
      },
    ],
  },
  pricing: {
    kicker: "Simple pricing",
    titleBefore: "You keep 100% of what your client ",
    titleAccent: "pays.",
    body: "Nthtake charges a simple monthly fee. No percentage taken from your client payments.",
    plans: [
      {
        name: "Free",
        price: "$0",
        period: "/ month",
        target: "For freelancers who want to try Nthtake.",
        features: [
          "1 active project",
          "Up to 10 GB storage",
          "Up to 3 takes/revisions per project",
          "Basic client preview",
          "Feedback and comments",
          "Payment unlock",
          "Nthtake watermark",
          "0% commission",
          "AI summaries not included",
        ],
        cta: "Start free",
        popular: false,
      },
      {
        name: "Pro",
        price: "$19",
        period: "/ month",
        target: "For freelancers using Nthtake regularly.",
        features: [
          "20 active projects",
          "250 GB storage",
          "Unlimited takes/revisions",
          "Client preview",
          "Feedback and comments",
          "Payment unlock",
          "100 AI summaries / month",
          "Custom watermark",
          "0% commission",
        ],
        cta: "Get Pro",
        popular: true,
      },
      {
        name: "Agency",
        price: "$49",
        period: "/ month",
        target: "For small creative teams and agencies.",
        features: [
          "Unlimited projects",
          "1 TB storage",
          "Unlimited takes/revisions",
          "Client preview",
          "Feedback and comments",
          "Payment unlock",
          "500 AI summaries / month",
          "3 team seats",
          "Custom watermark",
          "Priority support",
          "0% commission",
        ],
        cta: "Start with Agency",
        popular: false,
      },
    ],
    faqs: [
      {
        id: "p1",
        question: "Do you take a percentage of my client payments?",
        answer: "No. Nthtake takes 0% of your client payment. You pay a simple monthly fee.",
      },
      {
        id: "p2",
        question: "Can I use Nthtake for free?",
        answer: "Yes. The Free plan lets you try the core workflow with one active project.",
      },
      {
        id: "p3",
        question: "What are AI summaries?",
        answer: "They turn client feedback into a simple list of changes for your next version.",
      },
      {
        id: "p4",
        question: "Can I upgrade later?",
        answer: "Yes.",
      },
      {
        id: "p5",
        question: "What happens when I reach my storage limit?",
        answer: "You will need to free up storage or upgrade your plan.",
      },
    ],
  },
  closer: {
    kicker: "Stop chasing clients for payment",
    title: "Get early access to Nthtake.",
    body: "Stop chasing your own money. 0% commission on client payments.",
    emailLabel: "Work email",
    emailPlaceholder: "you@studio.com",
    craftLabel: "I am a",
    crafts: [
      { value: "video", label: "Video Editor" },
      { value: "design", label: "Graphic Designer" },
      { value: "agency", label: "Creative Agency" },
      { value: "other", label: "Other" },
    ],
    cta: "Get early access to Nthtake",
    sending: "Requesting",
    success: "Spot reserved for",
  },
  voices: {
    kicker: "Who it's for",
    titleBefore: "Built for freelancers who ",
    titleAccent: "deliver digital work.",
    body: "If you send large files to clients and need to get paid for them, Nthtake is for you.",
    items: [
      {
        id: 1,
        content: "Send cuts, collect feedback, get paid, release the master.",
        author: "Video editors",
        handle: "Premiere, DaVinci, Final Cut",
        platform: "dm" as const,
      },
      {
        id: 2,
        content: "Share previews, track changes, get approval, release final assets.",
        author: "Designers",
        handle: "Figma, Photoshop",
        platform: "tweet" as const,
      },
      {
        id: 3,
        content: "Keep client review, versions, approval, and payment in one place.",
        author: "Creative agencies",
        handle: "Client services",
        platform: "linkedin" as const,
      },
      {
        id: 4,
        content: "Upload the mix, let the client listen, and get paid before they download the WAV.",
        author: "Audio engineers",
        handle: "Pro Tools, Logic",
        platform: "dm" as const,
      },
      {
        id: 5,
        content: "Share the render, get notes on the lighting, lock the final file behind a payment.",
        author: "3D Artists",
        handle: "Blender, Cinema4D",
        platform: "tweet" as const,
      },
      {
        id: 6,
        content: "Deliver the graded timeline with a watermark, get the sign-off, get paid.",
        author: "Colorists",
        handle: "Resolve",
        platform: "dm" as const,
      },
    ],
  },
  footer: {
    blurb: "Send the client the work. Get paid. Then give them the clean files.",
    status: "Waitlist open",
    product: [
      { href: "#how", label: "How it works" },
      { href: "#feedback", label: "Feedback" },
      { href: "#pricing", label: "Pricing" },
      { href: "#questions", label: "Questions" },
    ],
    legal: [
      { href: "#", label: "Privacy" },
      { href: "#", label: "Terms" },
    ],
    company: [{ href: "#access", label: "Waitlist" }],
  },
};
